<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Siswa_model extends CI_Model
{

    public $table = 'ex_siswa';
    public $id = 'id_siswa';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_siswa', $q);
	$this->db->or_like('nama_siswa', $q);
	$this->db->or_like('jk', $q);
	$this->db->or_like('kelas', $q);
	$this->db->or_like('aqidaht1', $q);
	$this->db->or_like('aqidaht2', $q);
	$this->db->or_like('aqidahu', $q);
        $this->db->or_like('alqurant1', $q);
    $this->db->or_like('alqurant2', $q);
    $this->db->or_like('alquranu', $q);
        $this->db->or_like('alhaditst1', $q);
    $this->db->or_like('alhaditst2', $q);
    $this->db->or_like('alhaditsu', $q);
        $this->db->or_like('bat1', $q);
    $this->db->or_like('bat2', $q);
    $this->db->or_like('bau', $q);
        $this->db->or_like('akht1', $q);
    $this->db->or_like('akht2', $q);
    $this->db->or_like('akhu', $q);
        $this->db->or_like('skit1', $q);
    $this->db->or_like('skit2', $q);
    $this->db->or_like('skiu', $q);
        $this->db->or_like('fiqiht1', $q);
    $this->db->or_like('fiqiht2', $q);
    $this->db->or_like('fiqihu', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_siswa', $q);
	$this->db->or_like('nama_siswa', $q);
	$this->db->or_like('jk', $q);
	$this->db->or_like('kelas', $q);
	$this->db->or_like('aqidaht1', $q);
    $this->db->or_like('aqidaht2', $q);
    $this->db->or_like('aqidahu', $q);
        $this->db->or_like('alqurant1', $q);
    $this->db->or_like('alqurant2', $q);
    $this->db->or_like('alquranu', $q);
        $this->db->or_like('alhaditst1', $q);
    $this->db->or_like('alhaditst2', $q);
    $this->db->or_like('alhaditsu', $q);
        $this->db->or_like('bat1', $q);
    $this->db->or_like('bat2', $q);
    $this->db->or_like('bau', $q);
        $this->db->or_like('akht1', $q);
    $this->db->or_like('akht2', $q);
    $this->db->or_like('akhu', $q);
        $this->db->or_like('skit1', $q);
    $this->db->or_like('skit2', $q);
    $this->db->or_like('skiu', $q);
        $this->db->or_like('fiqiht1', $q);
    $this->db->or_like('fiqiht2', $q);
    $this->db->or_like('fiqihu', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    function get_siswakelas($limit, $start, $q) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('kelas', $q);
    
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    function total_rowskelas($kelas = NULL){
        $this->db->like('kelas', $kelas);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Siswa_model.php */
/* Location: ./application/models/Siswa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-10-16 11:20:58 */
/* http://harviacode.com */